const constants = {
    app_title: 'Blog App',
    email: 'Email',
    password: 'Password',
    enter_an_email: 'Enter an Email Address',
    enter_password: 'Enter your Password',
    login: 'Login',
    logout: 'Logout',
    create_an_account: 'Create An Account',
    name: 'Name',
    confirm_password: 'Confirm Password',
    re_enter_your_password: 'Re-enter Your Password',
    enter_you_name: "Enter Your Full Name",
    register: "Register",
    already_exist: 'Already have an account? Login',
    API_Error: 'API is not working properly',
    posts: 'Posts',
    comments: 'Comments',
    create_new_post: 'Create New Post',
    close_the_dialog: 'Dismiss',
    new_post: 'New Post',
    title: 'Title',
    body: 'Body',
    publish_the_post: 'Publish',
    edit: 'Edit',
    delete: 'Delete',
    edit_done: 'Done',
    go_back: 'Back to posts',
    post: 'Post',
    loading: 'Loading...',
    publish_the_comment: 'Publish Comment',
    add_new_comment: 'Add New Comment',
    post_title: 'Title: ',
    post_body: 'Body: ',
    something_went_wrong: 'Something went wrong.',
    my_profile: 'My Profile',
    loginFirst: 'Login first to check comments',
    like: 'Like',
    unlike: 'Unlike'
}

export default constants