const constants = {
    something_went_wrong: 'Something went wrong',
    updated: 'Updated',
    deleted: 'Deleted',
    commented: 'Commented',
    user_already_exists: 'User already exists',
    posted: 'Posted',
    add_all_fields: 'Please add all fields',
    invalid_user_data: 'Invalid user data',
    incorrect_email_or_password: 'Incorrect email or password',
    enter_name: 'Please add a name',
    enter_email: 'Please enter email',
    enter_password: 'Please enter password',
    not_auth_no_token: 'Not authorized, no token',
    not_authorized: 'Not Authorized',
    minus_password: '-password',
    bearer: 'Bearer',
    enter_title: 'Please add title',
    enter_body: 'Please add body',
    enter_comment: 'Please add comment',
    comments: 'comments',
    posts: 'posts',
    users: 'users',
    cant_get_individual_post: 'Cant get single post',
    edit_failed: 'Edit Failed',
    deletion_failed: 'Deletion Failed',
    publish_new_post_failed: 'Cant publish new post',
    publish_new_comment_failed: 'Cant publish new comment',
    login_failed: 'Login failed',
    signup_failed: 'Signup failed',
    profile_data_failed: 'Profile data loading failed',
    post_fetch_failed: 'Cant fetch all posts',
    comments_fetch_failed: 'Cant fetch all comments'
}

module.exports = constants